name: filla_flow
description: "Filla Flow – A Flutter library with custom widgets based on Material Design."
version: 0.0.4
homepage: https://github.com/benitoanagua/FillaFlow

environment:
  sdk: ^3.9.2
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
