name: widgetbook_workspace
description: "Filla Flow Widget Catalog"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.7.0
  widgetbook_annotation: ^3.7.0
  filla_flow:
    path: ../packages/filla_flow

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  widgetbook_generator: ^3.17.0
  build_runner: ^2.9.0

flutter:
  uses-material-design: true
